### ISSUE TITLE
root numpy name conflict

### ISSUE THREAD

**Issue by tunnell** [remenska/conda-recipes#3]
I see two versions of root numpy on people's machines (one anaconda and one through pip).  I think this comes from pip using a dash (root-numpy) and anaconda using an underscore (root_numpy).

**Comment by remenska** [comment]
Yes I've noticed this too, but I'm not sure how to solve it. The problem is, rootpy in their git repository state the root_numpy as a requirement, so the conda build of rootpy (which is done with python setup.py install in the background) picks it up with pip. 

Any idea? I guess we cannot tell rootpy people to change their requirements just because we use conda installs. I can remove root-numpy requirement in the conda recipe of building root, so then it's picked up by pip. But on the other hand, with conda I try to build against the latest master branch of root_numpy, with pip that is not always the case I guess.

**Comment by tunnell** [comment]
Let's just ask rootpy people why it's that way?

**Comment by remenska** [comment]
But this is just because they want the ability to grab and compile rootpy outside of anaconda?

**Comment by remenska** [comment]
Oh wait, maybe if I change root_numpy conda package to root-numpy the conda one will be picked up instead. The dependency will be automatically met. 

Let me see when I have a clearer head, just back from 8 hours of training.

But this shouldn't be a showstopper at the moment.

**Comment by tunnell** [comment]
not an issue, just weird.  can be thought about next week

**Comment by remenska** [comment]
Renaming root_numpy to root-numpy solves the issue. The pip version is no longer fetched.
